language: ruby
sudo: false
cache: bundler
rvm:
  - 2.6.6
before_install:
  - gem update --system
gemfile:
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_6_1.gemfile
  - gemfiles/rails_7_0.gemfile
  - gemfiles/rails_7_1.gemfile
