language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.7
  - 2.3.4
gemfile:
  - gemfiles/rails_4.0.13.gemfile
  - gemfiles/rails_4.1.15.gemfile
  - gemfiles/rails_4.2.8.gemfile
  - gemfiles/rails_5.0.2.gemfile
  - gemfiles/rails_5.1.0.gemfile

matrix:
  include:
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4.2.8.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_5.0.2.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_5.1.0.gemfiles
