name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  standard:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:
      - name: Standard Ruby
        uses: standardrb/standard-ruby-action@v1
        with:
          autofix: false
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.2.5", "3.3.5"]
        gemfile: [rails_6_0, rails_6_1, rails_7_0, rails_7_1, rails_7_2]
        exclude:
          - ruby: "2.7.8"
            gemfile: rails_7_0
          - ruby: "2.7.8"
            gemfile: rails_7_1
          - ruby: "2.7.8"
            gemfile: rails_7_2

    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rspec
