name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  standard:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Standard Ruby
        uses: standardrb/standard-ruby-action@eecb3f730879f5b8830705348c2961e5aa26de78 # v1.5.0
        with:
          autofix: false
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3.11", "3.4.9", "4.0.5"]
        gemfile: [rails_7_1, rails_7_2, rails_8_0, rails_8_1]
        exclude:
          - ruby: "3.3.11"
            gemfile: rails_8_0
          - ruby: "3.3.11"
            gemfile: rails_8_1
          - ruby: "4.0.5"
            gemfile: rails_7_1
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rspec
